name: build
on:
  push:
    branches: ["main", "*.x-line"]
    tags: ["*"]
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "3.9", python: "3.9", tox: py39-marshmallow3 }
          - { name: "3.13", python: "3.13", tox: py313-marshmallow3 }
          - { name: "lowest", python: "3.9", tox: py39-lowest }
          - { name: "dev", python: "3.13", tox: py313-marshmallowdev }
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: python -m pip install --upgrade pip
      - run: python -m pip install tox
      - run: python -m tox -e ${{ matrix.tox }}
  # this duplicates pre-commit.ci, so only run it on tags
  # it guarantees that linting is passing prior to a release
  lint-pre-release:
    name: lint
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install tox
      - run: python -m tox -e lint
  release:
    needs: [tests, lint-pre-release]
    name: PyPI release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
      - name: install requirements
        run: python -m pip install build twine
      - name: build dists
        run: python -m build
      - name: check package metadata
        run: twine check dist/*
      - name: publish
        run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
